name: Publish to server

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samsqd
          password: SaintSquad.12
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: samsqd/bot

  server_update:
    needs: docker
    name: Update server buy ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.41.160.212
          port: 22
          username: root
          password: SaintSquad.12
          script_stop: true
          script: |
            echo "Stop container"
            docker stop bot
            docker rm bot
            docker image rm samsqd/bot
            echo "Pull image"
            docker pull samsqd/bot
            echo "Start container"
            docker run --name bot -t -d samsqd/bot
            echo "Finish deploying!"
