name: Publish to server

on:
  push:
    branches: [ "master" ]

jobs:
  server_update:
    name: Update server buy ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.41.160.212
          port: 22
          username: root
          password: SaintSquad.12
          script_stop: true
          script: |
            echo "Download from git"
            cd TGBotWork
            git fetch
            echo "DOCKER"
            docker stop bot
            docker rm bot
            docker image rm bot
            docker build -t image_bot .
            docker run --name bot -d -t image_bot
            echo "Finish deploying!"